# Generated by Django 3.2.8 on 2021-10-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sanctuary', '0002_player_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
